# Generated by Django 3.0 on 2020-05-27 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('informer_name', models.CharField(default='', max_length=300)),
                ('informer_mobile', models.CharField(default='', max_length=11)),
                ('suspect_mobile', models.CharField(default='', max_length=11)),
                ('suspect_name', models.CharField(default='', max_length=300)),
                ('suspect_adress', models.CharField(default='', max_length=1000)),
            ],
        ),
    ]
